// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNLit1zbMWu7ZWl7KjpbzhdP7eMeDs5Ew',
    appId: '1:90711049385:android:6bfd896c251cfbc0c255b8',
    messagingSenderId: '90711049385',
    projectId: 'rurall-apk-01202-1580563139830',
    databaseURL: 'https://rurall-apk-01202-1580563139830.firebaseio.com',
    storageBucket: 'rurall-apk-01202-1580563139830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsbk_JIjnSWjbRiEgW_0YUPIHXJopV_Z4',
    appId: '1:90711049385:ios:fa343547768233bdc255b8',
    messagingSenderId: '90711049385',
    projectId: 'rurall-apk-01202-1580563139830',
    databaseURL: 'https://rurall-apk-01202-1580563139830.firebaseio.com',
    storageBucket: 'rurall-apk-01202-1580563139830.appspot.com',
    androidClientId: '90711049385-mmr09al1r323aq904rq1prigfeemjrhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.rurallstrong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsbk_JIjnSWjbRiEgW_0YUPIHXJopV_Z4',
    appId: '1:90711049385:ios:fa343547768233bdc255b8',
    messagingSenderId: '90711049385',
    projectId: 'rurall-apk-01202-1580563139830',
    databaseURL: 'https://rurall-apk-01202-1580563139830.firebaseio.com',
    storageBucket: 'rurall-apk-01202-1580563139830.appspot.com',
    androidClientId: '90711049385-mmr09al1r323aq904rq1prigfeemjrhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.rurallstrong',
  );
}
